In [9]:
import numpy as np
arr = np.array([[7,8,9],[10,11,12]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.itemsize)
print(arr.dtype)
print(arr.nbytes)
print(arr.strides)

(2, 3)
6
2
8
int64
48
(24, 8)


In [10]:
import numpy as np
myarr=np.array([12,7,8,9,12],dtype='int64')
myarr

array([12,  7,  8,  9, 12])

In [11]:
import numpy as np

Data type Conversion

In [14]:
arr=np.array([12.5,6.89,9.84,6.78],dtype='float32')
arr2=arr.astype('int64')
arr2

array([12,  6,  9,  6])

In [20]:
x=np.zeros([5,3,2])
x2=np.ones([3,4])
x3=np.identity(4)
x4=np.eye(4,k=1)
x4

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [24]:
arr=np.arange(10,2,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3])

RANDOM NUMBERS

In [29]:
arr=np.random.randint(0,10,size=5)
arr

array([3, 6, 7, 9, 4])

SLICING

In [40]:
arr=np.array([[12,4,5,6],[5,6,7,8],[1,2,3,16],[1,2,3,4]])
print(arr[:,3])

[ 6  8 16  4]


BOOLEAN INDEXING

In [46]:
arr=np.array([15,22,30,8,45,12,60])
mask=arr>25
print(mask)
m2=(arr<20)|(arr>50)
print(arr[m2])

[False False  True False  True False  True]
[15  8 12 60]


CONDITIONAL STATEMENTS

In [49]:
arr=np.array([10,25,30,45,50])
res=np.where(arr<20,"small",np.where(arr<40,"medium","large"))
print(res)

['small' 'medium' 'medium' 'large' 'large']


In [53]:
arr=np.array([10,20,25,40,55])
res=np.where(arr%2==0,"even","odd")
print(res)
res1=np.where((arr>10)&(arr<40))
print(res1)
res2=np.where(arr<20,"Low",np.where(arr<40,"Medium","High"))
print(res2)

['even' 'even' 'odd' 'even' 'odd']
(array([1, 2]),)
['Low' 'Medium' 'Medium' 'High' 'High']


NUMPY SELECT FUNCTION

In [54]:
arr=np.array([10,45,25,30,45,50])
cons=[arr<20,
      (arr>=20)&(arr<40),
      arr>=40]
sel=["small","medium","large"]
res=np.select(cons,sel,default="Unknown")
print(res)

['small' 'large' 'medium' 'medium' 'large' 'large']


ARRAY RESHAPE

In [57]:
arr=np.arange(12)
rs=arr.reshape(4,-1)
print(rs)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [62]:
arr=np.arange(2,20,2)
arr=arr.reshape(3,3)
print(arr.flatten())

[ 2  4  6  8 10 12 14 16 18]
